networks:
  zookeeper:
    driver: bridge
  producer-zookeeper:
    driver: bridge
  producer:
    driver: bridge
  consumer:
    driver: bridge
  consumer-zookeeper:
    driver: bridge

services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
    networks:
      - zookeeper
      - producer-zookeeper
      - consumer-zookeeper

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
    networks:
      - zookeeper
      - producer-zookeeper
      - consumer-zookeeper

  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2183:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
    networks:
      - zookeeper
      - producer-zookeeper
      - consumer-zookeeper

  zk_web:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator
    ports:
      - 9090:9090
    environment:
      - HTTP_PORT=9090
    depends_on:
      - zookeeper-1
    links:
      - zookeeper-1
    networks:
      - zookeeper

  producer-1:
    hostname: producer-1
    image: producer
    build:
      context: service-producer
    ports:
      - "8081:8080"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    networks:
      - producer
      - producer-zookeeper

  producer-2:
    hostname: producer-2
    image: producer
    build:
      context: service-producer
    ports:
      - "8082:8080"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    networks:
      - producer
      - producer-zookeeper

  producer-3:
    hostname: producer-3
    image: producer
    build:
      context: service-producer
    ports:
      - "8083:8080"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    networks:
      - producer
      - producer-zookeeper

  consumer:
    image: service-consumer
    build:
      context: serviceconsumer
    ports:
      - "8084:8080"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    networks:
      - consumer
      - consumer-zookeeper
      - producer-zookeeper