networks:
  zookeeper:
    driver: bridge
  producer-zookeeper:
    driver: bridge
  producer:
    driver: bridge
  consumer:
    driver: bridge
  consumer-zookeeper:
    driver: bridge
  kafka-zookeeper:
    driver: bridge
  kafka:
    driver: bridge
  producer-kafka:
    driver: bridge
  consumer-kafka:
    driver: bridge
  producer-mongodb:
    driver: bridge
  consumer-mongodb:
    driver: bridge
volumes:
  mongodb-data:
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
    networks:
      - zookeeper
      - producer-zookeeper
      - consumer-zookeeper
      - kafka-zookeeper

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
    networks:
      - zookeeper
      - producer-zookeeper
      - consumer-zookeeper
      - kafka-zookeeper

  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2183:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
    networks:
      - zookeeper
      - producer-zookeeper
      - consumer-zookeeper
      - kafka-zookeeper

  zk_web:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator
    ports:
      - 9090:9090
    environment:
      - HTTP_PORT=9090
    depends_on:
      - zookeeper-1
    links:
      - zookeeper-1
    networks:
      - zookeeper

  producer-1:
    hostname: producer-1
    image: producer
    build:
      context: service-producer
    ports:
      - "8081:8080"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=events
    networks:
      - producer
      - producer-zookeeper
      - producer-kafka
      - producer-mongodb

  producer-2:
    hostname: producer-2
    image: producer
    build:
      context: service-producer
    ports:
      - "8082:8080"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=events
    networks:
      - producer
      - producer-zookeeper
      - producer-kafka
      - producer-mongodb

  producer-3:
    hostname: producer-3
    image: producer
    build:
      context: service-producer
    ports:
      - "8083:8080"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=events
    networks:
      - producer
      - producer-zookeeper
      - producer-kafka
      - producer-mongodb

  consumer:
    image: service-consumer
    build:
      context: serviceconsumer
    ports:
      - "8084:8080"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=events
    networks:
      - consumer-zookeeper
      - consumer
      - consumer-mongodb
      - consumer-kafka

  kafka-1:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183"
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    networks:
      - kafka-zookeeper
      - kafka
      - consumer-zookeeper
      - producer-kafka
      - consumer-kafka
  kafka-2:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9093:9093"
      - "29093:29093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:19093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093,DOCKER://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_BROKER_ID: 2
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    networks:
      - kafka-zookeeper
      - kafka
      - consumer-zookeeper
      - producer-kafka
      - consumer-kafka

  kafka-3:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9094:9094"
      - "29094:29094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:19094,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094,DOCKER://localhost:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_BROKER_ID: 3
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    networks:
      - kafka-zookeeper
      - kafka
      - consumer-zookeeper
      - producer-kafka
      - consumer-kafka
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8085:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: cqrs_ui
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:19092,kafka-2:19093,kafka-3:19094
    networks:
      - kafka
      - kafka-zookeeper
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - producer
      - consumer
      - producer-mongodb
      - consumer-mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=events