logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN
spring:
  cloud:
    zookeeper:
      connect-string: localhost:2181,localhost:2182,localhost:2183
  data:
    mongodb:
      host: localhost
      port: 27017
      database: "events"
  kafka:
    bootstrap-servers: "localhost:29092,localhost:29093,localhost:29094"

mongo:
  host: localhost